# Generated by Django 6.1.1 on 2026-09-15 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='thb', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid'])), name='order_status_valid'), models.CheckConstraint(condition=models.Q(('status', 'pending'), ('paid_at__isnull', False), _connector='OR'), name='order_paid_has_paid_at')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('card', 'Card'), ('promptpay', 'Promptpay')], max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('charge_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('needs_refund', models.BooleanField(default=False)),
                ('authorize_uri', models.URLField(blank=True, max_length=2048, null=True)),
                ('qr_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='payment_status_expires_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('needs_refund', False), ('status', 'successful')), fields=('order',), name='one_effective_successful_payment_per_order'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'successful', 'failed', 'expired'])), name='payment_status_valid'), models.CheckConstraint(condition=models.Q(('method__in', ['card', 'promptpay'])), name='payment_method_valid'), models.CheckConstraint(condition=models.Q(('needs_refund', False), ('status', 'successful'), _connector='OR'), name='payment_refund_only_when_successful')],
            },
        ),
    ]
